import java.awt.event.ActionEvent;
/*A semantic event which indicates that a component-defined action occured. This high-level event is generated by a component (such as a Button) when the component-specific action occurs (such as being pressed). The event is passed to every every ActionListener object that registered to receive such events using the component's addActionListener method. */
import org.cytoscape.application.swing.AbstractCyAction;
/*An interface that describes how an action should be placed within the menus and/or toolbars of the Swing application.*/
import org.cytoscape.app.CyAppAdapter;
import org.cytoscape.application.CyApplicationManager;
import org.cytoscape.model.CyEdge;
import org.cytoscape.model.CyNetwork;
import org.cytoscape.model.CyNode;
import org.cytoscape.view.model.CyNetworkView;
import org.cytoscape.view.presentation.property.BasicVisualLexicon;


public class MenuAction extends AbstractCyAction
{
	private final CyAppAdapter adapter;
	
	public MenuAction(CyAppAdapter adapter)
	{
		super("Hide unconnected nodes", adapter.getCyApplicationManager(),"network",adapter.getCyNetworkViewManager());
		this.adapter = adapter;
		setPreferredMenu("Select");
	}
	
	public void actionPerformed(ActionEvent e)
	{
		final CyApplicationManager manager = adapter.getCyApplicationManager();
		final CyNetworkView networkView = manager.getCurrentNetworkView();
		final CyNetwork network = networkView.getModel();
		
		for(CyNode node : network.getNodeList())
		{
			if(network.getNeighborList(node, CyEdge.Type.ANY).isEmpty())
			networkView.getNodeView(node).setVisualProperty(BasicVisualLexicon.NODE_VISIBLE, false);
		}
		
		networkView.updateView();
	}
	
}